<?php

$portfolioFilters = [
    'cat-web' => 'Web Apps',
    'cat-mobile' => 'Mobile',
    'cat-ai' => 'AI & ML',
    'cat-cloud' => 'Cloud',
    'cat-design' => 'UI/UX',
];

$portfolioItems = [
    [
        'slug' => 'fintrack-dashboard',
        'title' => 'FinTrack Dashboard',
        'category' => 'Web App AI',
        'filters' => 'cat-web cat-ai',
        'image' => 'assets/img/portfolio/port-1.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '0',
    ],
    [
        'slug' => 'pulse-health-app',
        'title' => 'Pulse Health App',
        'category' => 'Mobile iOS & Android',
        'filters' => 'cat-mobile',
        'image' => 'assets/img/portfolio/port-2.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '100',
    ],
    [
        'slug' => 'auroramart-platform',
        'title' => 'AuroraMart Platform',
        'category' => 'E-Commerce Cloud',
        'filters' => 'cat-cloud cat-web',
        'image' => 'assets/img/portfolio/port-3.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '200',
    ],
    [
        'slug' => 'visionsort-ai-system',
        'title' => 'VisionSort AI System',
        'category' => 'AI Computer Vision',
        'filters' => 'cat-ai',
        'image' => 'assets/img/portfolio/port-4.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '0',
    ],
    [
        'slug' => 'zena-saas-platform',
        'title' => 'Zena SaaS Platform',
        'category' => 'SaaS UI/UX',
        'filters' => 'cat-design cat-web',
        'image' => 'assets/img/portfolio/port-5.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '100',
    ],
    [
        'slug' => 'cloudnest-infrastructure',
        'title' => 'CloudNest Infrastructure',
        'category' => 'Cloud DevOps',
        'filters' => 'cat-cloud',
        'image' => 'assets/img/portfolio/port-6.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '200',
    ],
    [
        'slug' => 'nomad-travel-app',
        'title' => 'Nomad Travel App',
        'category' => 'Mobile UI/UX',
        'filters' => 'cat-mobile cat-design',
        'image' => 'assets/img/portfolio/port-7.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '0',
    ],
    [
        'slug' => 'orbit-content-platform',
        'title' => 'Orbit Content Platform',
        'category' => 'Web App Design',
        'filters' => 'cat-web cat-design',
        'image' => 'assets/img/portfolio/port-8.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '100',
    ],
    [
        'slug' => 'synthex-data-engine',
        'title' => 'Synthex Data Engine',
        'category' => 'AI Data Engineering',
        'filters' => 'cat-ai cat-cloud',
        'image' => 'assets/img/portfolio/port-9.jpg',
        'url' => 'portfolio-single.php',
        'delay' => '200',
    ],
];

foreach ($portfolioItems as &$portfolio) {
    $portfolio['details'] = [
        'tag' => $portfolio['category'],
        'summary' => 'A focused digital solution designed to help the client improve performance, streamline operations, and create a better customer experience.',
        'lead' => $portfolio['title'] . ' was created to solve a complex business challenge with a reliable, scalable, and easy-to-use digital experience.',
        'challenge_title' => 'The Challenge',
        'challenge' => 'The client needed a modern solution that could replace inefficient workflows, support growth, and give their team better visibility and control.',
        'challenge_points' => [
            'Inefficient legacy workflows were slowing down daily operations',
            'Limited visibility made it difficult to make timely decisions',
            'The existing experience could not scale with customer and business growth',
        ],
        'approach_title' => 'Our Approach',
        'approach' => 'We combined discovery, user-focused design, and modern engineering practices to build a practical solution around the client\'s most important goals.',
        'approach_points' => [
            'Discovery and planning to define business goals and technical requirements',
            'A scalable architecture designed around performance, security, and maintainability',
            'Iterative delivery with testing and feedback throughout the project',
        ],
        'gallery' => [],
        'quote' => '',
        'quote_author' => '',
        'results_summary' => 'Delivered with a stable foundation for continued growth, improved operational visibility, and a smoother experience for customers and internal teams.',
        'results' => [
            ['value' => '2x', 'label' => 'Faster Workflows', 'description' => 'Reduced friction across the most important user journeys'],
            ['value' => '99.9%', 'label' => 'Platform Reliability', 'description' => 'Built for dependable day-to-day business operations'],
            ['value' => '100%', 'label' => 'Responsive Design', 'description' => 'Consistent experience across desktop, tablet, and mobile'],
        ],
        'client' => 'Confidential Client',
        'year' => '2024',
        'duration' => '6 Months',
        'team_size' => '8 People',
        'location' => 'United States',
        'live_url' => '',
    ];
}
unset($portfolio);

$portfolioItems[0]['details'] = [
    'tag' => 'Web App / AI & ML / FinTech',
    'summary' => 'From a crumbling 12-year-old PHP codebase to a real-time AI analytics platform processing $2 billion in daily transactions.',
    'lead' => 'FinTrack came to NexVera with a critical problem: their legacy financial dashboard was built on a 12-year-old PHP codebase that was crashing under load, costing $400K per year just to maintain, and completely unable to process real-time data.',
    'challenge_title' => 'The Challenge',
    'challenge' => 'Leadership issued a bold mandate: rebuild the entire platform in under 6 months, maintain 100% data fidelity during migration, and add AI-powered forecasting - all while keeping the existing system live for 8,000 daily active enterprise users.',
    'challenge_points' => [
        '$400K annual maintenance burden from vendor lock-in, custom patches, and 12 years of technical debt',
        'Zero real-time capability — batch jobs running every 4 hours meant enterprise clients made decisions on stale data',
        '8,000 users, zero downtime allowed - enterprise SLAs made a "big bang" cutover impossible',
        '14 third-party integrations wired directly into monolithic code with no documented contracts',
    ],
    'approach_title' => 'Our Approach',
    'approach' => 'We ran a 4-week Discovery sprint before writing a single line of new code - fully mapping data architecture, API contracts, and user journeys across all 14 financial data providers.',
    'approach_points' => [
        'Discovery Sprint - Full audit of data flows and API contracts. Produced a zero-ambiguity technical blueprint in 4 weeks.',
        'Strangler-Fig Migration - Incremental module shipping with progressive traffic routing. Zero-downtime migration over 18 weeks.',
        'AI Forecasting Module - Fine-tuned TimesGPT on 8 years of historical data, achieving 94% accuracy on 30-day cash-flow forecasts.',
        'Cohort Rollout & QA - Feature-flagged rollout with live rollback. 100% data fidelity verified at every migration stage.',
    ],
    'gallery' => [
        ['image' => 'assets/img/portfolio/port-4.jpg', 'alt' => 'AI Forecasting Module', 'description' => 'AI Forecasting module - 30-day cash-flow prediction charts'],
        ['image' => 'assets/img/portfolio/port-5.jpg', 'alt' => 'Mobile View', 'description' => 'Mobile responsive view - iOS and Android optimised'],
    ],
    'quote' => 'NexVera did not just rebuild our platform - they transformed our product entirely. The AI forecasting alone has become our biggest sales differentiator. We closed a $3M enterprise deal last month where the buyer specifically cited it.',
    'quote_author' => 'Marcus Webb - Chief Executive Officer, FinTrack Inc.',
    'results_summary' => 'Delivered in 6 months. Maintained 100% data fidelity throughout. Zero unplanned downtime on launch day.',
    'results' => [
        ['value' => '340%', 'label' => 'User Engagement', 'description' => 'Daily active sessions surged within 60 days of launch'],
        ['value' => '99.99%', 'label' => 'Platform Uptime', 'description' => 'Maintained across 8,000 enterprise users with no SLA penalties'],
        ['value' => '60%', 'label' => 'Cost Reduction', 'description' => 'From $400K annual maintenance to under $160K'],
    ],
    'client' => 'FinTrack Inc.',
    'year' => '2024',
    'duration' => '6 Months',
    'team_size' => '10 People',
    'location' => 'New York, USA',
    'live_url' => 'https://fintrack.io',
];
